### ISSUE TITLE
Get GPS info from user

### ISSUE THREAD

**Issue by bgoodwine** [NDEats/NDEats-Front-End#2]
Tutorial: https://dev.to/codebubb/how-to-get-a-user-s-location-with-javascript-362o
(Sorry in advance idk how JS works rip)

Can you fix this code so that there will be a request with geo information if the user allows gps info and a request without gps information if the user does not? 
https://github.com/NDEats/NDEats-Front-End/blob/351654ab374cba48eb48af30c96eb0c71cc73f53/nd-eats-front/src/components/Orders.js#L22-L38

**Comment by jeanfboueri** [comment]
Helpful: 
https://www.pluralsight.com/guides/how-to-use-geolocation-call-in-reactjs
https://javascript.plainenglish.io/how-to-use-the-geolocation-api-in-your-react-app-54e87c9c6c94
https://dev.to/codebucks/how-to-get-user-s-location-in-react-js-1691

**Comment by jeanfboueri** [comment]
https://dev.to/codebucks/how-to-get-user-s-location-in-react-js-1691
